### ISSUE TITLE
getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by saqibomer** [131/icloud-api#5]
I am using express js. After storing session file I am trying to get contacts and it is giving me this error.
`events.js:160
      throw er; // Unhandled 'error' event`
`Error: getaddrinfo ENOTFOUND p59-photosws.icloud.com p59-photosws.icloud.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)`

How can I fix this?

**Comment by tbain98** [comment]
I'm seeing the same issue, over a year later. Maybe this library's no longer being maintained?

**Comment by 131** [comment]
I'll try to look at it if i can find some time 😪
